site_name: TheH4ckademy

theme:
  name: shadcn
  language: en

nav:
  - ðŸ§  TheH4ckademy: index.md
  - TryHackMe: 
    - TryHackMe/reset.md
    - TryHackMe/ledger.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.snippets

